### ISSUE TITLE
Particle blood

### ISSUE THREAD

**Issue by MrJimbones** [NobleMuffins/LimbHacker#1]
Hi, sorry for leaving this as an issue, but I haven't been able to reach anyone via suggested usual contact methods. I understand that this asset is a bit old, but I was hoping to find some more detailed information on how to best spawn some blood particles at the slice point. I've tried a few different things but nothing seems to be working for me. Any information would be extremely appreciated. Thank you! :)

**Comment by MrJimbones** [comment]
Oops..I should mention that ideally I'm looking for a way for the particle effect object to be attached to the sliced limb of the ragdoll being spawned.

**Comment by JoeCooper** [comment]
Hey, thanks for writing. I'm not sure how I missed a message if you wrote in via e-mail, but this now is the ideal place to go for Limb Hacker.

Limb Hacker is still supported. Did you buy through Unity Asset Store? Do you have an invoice?

**Comment by MrJimbones** [comment]
Oh hey sorry Joe,
I wasn't really sure how you guys were handling it. I just got it from here on git so I don't have an invoice. Haha..Guess I'm on my own then for figuring this out yea?

**Comment by JoeCooper** [comment]
Maybe!

For this now I charge for particular changes as a freelancer. In fact, the last two big changes (including the update to use asynchronous slice) were done like this. I could for example write this into the readme as a freelance job.

It does seem like a simple question, but unfortunately I’d have to open it up and dig a bit (I haven’t touched it in months) and at this moment I’m so busy I have to be a little bit of a tight-ass about it.

WDYT?

**Comment by JoeCooper** [comment]
Oh, also, at a glance it looks like I’ve set up the ability to do this and there’s a hole in the readme.

Start here:

https://github.com/NobleMuffins/LimbHacker/blob/master/Guts/SliceEventArgs.cs

You can get a callback via multicast delegate that has the two result objects and the orientation and focal point of the slice. In theory that’s all you need.

I don’t know your experience level with C#, though. Do you need more hands-on help?

**Comment by MrJimbones** [comment]
Hey thanks Joe!
I may just end up taking you up on that offer at some point. Given that my c# fu is still in it's young Grasshopper stage, this particular issue is proving to be a pretty good learning experience.
I'm gonna go ahead and take a few more cracks at it first and I'll get back to you if (when? Haha) I get whupped. XD 
Thanks for the tip there on where I might start looking! Definitely appreciated. 
The system is really cool man. Good on you for making it. ;)
It's working really well for my VR project (Vive & Rift) over the Photon network. Good stuff. :D

**Comment by JoeCooper** [comment]
Looks like there’s nothing in the examples either about that multicast delegate. If you google “multicast delegate” and read up and then search the code for references to SliceEventArgs in the Limb Hacker sources than it will help make sense.

**Comment by JoeCooper** [comment]
Also, thanks for the kind words. I’m really glad you like it. It never worked out like I hoped but as a piece of code it might be the one I’m most proud of.

**Comment by JoeCooper** [comment]
@MrJimbones did this work out for you?

**Comment by MrJimbones** [comment]
Oh hey Joe,
Sorry for not getting back about it sooner. not yet sadly.. 
I gave it a couple of shots but wasn't able to figure it out yet. That's some pretty intense code man! haha
I've been spending almost all my time over the past few weeks multiplayer networking my game so I haven't had much more than a little bit of time to work on it. Just got that all going about an hour ago (thank god...lol) though so I can look into it a bit more diligently over the next few days. :)

**Comment by MrJimbones** [comment]
Getting closer Joe. ;)
I've got the particles to spawn in the proper place, just need to figure out how to stick em' to the alpha/bravo ragdolls. :D

**Comment by MrJimbones** [comment]
Haha...oh man sorry Joe. Don't know how or when it happened, but I must've accidentally clicked something on here and made a repo. Not sure how to undo that...haha

**Comment by JoeCooper** [comment]
What like a fork? Are you new to GitHub?

**Comment by MrJimbones** [comment]
Yeah kinda.

**Comment by JoeCooper** [comment]
That's no problem. Basically if you make a change, you can make a commit to
your own repository, and then you can send a "pull request" to me and I can
merge in your changes into my own repository. This latter part is optional
though and the idea that mine is the "main" repository is a social
convention.

Just remember to respect copyright; most projects will have an explicit
license, usually in the repo's root, that says what you can do with it.

**Comment by MrJimbones** [comment]
Ah k. Not so sure you'd be interested in any changes I would be making. XD
Having enough trouble as it is with the hack job I'm doing just trying to get this blood particle stuff to work. (Limb Hacker in deed) :p

**Comment by MrJimbones** [comment]
Hi Joe. I finally got around to figuring this out so you can close the issue if you like. Ended up building an external solution based on hits/colliders. The ragdoll has a script that grabs the information about where the hit happened upon instantiation and then turns on the appropriate blood particle object that's attached to the ragdoll. Thanks again for LimbHacker, and have a great day! :D
